### ISSUE TITLE
Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'NoneType'>

### ISSUE THREAD

**Issue by jballhalla** [tgweber/fosc#8]
I cloned fosc and attempted to run the provided [Quick Start](https://github.com/tgweber/fosc#quick-start) code. [python==3.7.12, tensorflow==2.5.0, scikit-learn==0.21.3]

Returns 'ValueError: Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'NoneType'>'

Code and error message printed below. I hope to implement fosc to determine the disciplines of >25,000 as of yet unstudied open access journals published using [Open Journal Systems](https://pkp.sfu.ca/ojs/), the world's largest open source academic publishing software. Seems like a perfect use case for fosc.

```python
import pandas as pd
from fosc import load_model, vectorize
from fosc.config import config

model_id = 'mlp_l'
model = load_model(model_id)

df = pd.DataFrame(
    [
        { "id": "Information and Computer Science Example",
          "payload": "Automated classification of metadata of research" \
                     " data by their discipline(s) of research can be used" \
                     " in scientometric research, by repository service providers," \
                     " and in the context of research data aggregation services." \
                     " Openly available metadata of the DataCite index for research"\
                     " data were used to compile a large training and evaluation set" \
                     " comprised of 609,524 records, which is published alongside this" \
                     " paper. These data allow to reproducibly assess classification" \
                     " approaches, such as tree-based models and neural networks." \
                     " According to our experiments with 20 base classes (multi-label" \
                     " classification), multi-layer perceptron models perform best with" \
                     " a f1-macro score of 0.760 closely followed by Long Short-Term Memory" \
                     " models (f1-macro score of 0.755). A possible application of the" \
                     " trained classification models is the quantitative analysis of trends" \
                     " towards interdisciplinarity of digital scholarly output or the" \
                     " characterization of growth patterns of research data, stratified" \
                     " by discipline of research. Both applications perform at scale with" \
                     " the proposed models which are available for re-use."
         } 
    ]
)

vectorized = vectorize(df.payload, model_id).sort_indices()
preds = pd.DataFrame(model.predict(vectorized))
df = df.join(preds)
```

Error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/jd/xc5v3g2j5nz52rmv0jd4dn8h0000gn/T/ipykernel_12998/3228237123.py in <module>
     32 
     33 vectorized = vectorize(df.payload, model_id).sort_indices()
---> 34 preds = pd.DataFrame(model.predict(vectorized))
     35 df = df.join(preds)
     36 df

~/opt/anaconda3/envs/OJSGlobal/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1704           use_multiprocessing=use_multiprocessing,
   1705           model=self,
-> 1706           steps_per_execution=self._steps_per_execution)
   1707 
   1708       # Container that configures and calls `tf.keras.Callback`s.

~/opt/anaconda3/envs/OJSGlobal/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py in get_data_handler(*args, **kwargs)
   1362   if getattr(kwargs["model"], "_cluster_coordinator", None):
   1363     return _ClusterCoordinatorDataHandler(*args, **kwargs)
-> 1364   return DataHandler(*args, **kwargs)
   1365 
   1366 

~/opt/anaconda3/envs/OJSGlobal/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)
   1150       self._steps_per_execution_value = steps_per_execution.numpy().item()
   1151 
-> 1152     adapter_cls = select_data_adapter(x, y)
   1153     self._verify_data_adapter_compatibility(adapter_cls)
   1154     self._adapter = adapter_cls(

~/opt/anaconda3/envs/OJSGlobal/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
    992         "Failed to find data adapter that can handle "
    993         "input: {}, {}".format(
--> 994             _type_name(x), _type_name(y)))
    995   elif len(adapter_cls) > 1:
    996     raise RuntimeError(

ValueError: Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'NoneType'>
```

**Comment by tgweber** [comment]
Hi, thank you for your interest and bug report. It's been a while that I had had a look at the code, but I will try to look into your issue asap.

For a quick and dirty fix, it might be necessary to change back to an unsecure tensorflow version. I need some time to look into it.

**Comment by tgweber** [comment]
Should be fixed by latest version (there are warning left, but the quickstart should work again).

Can you confirm  @j-a-ball ?

**Comment by jballhalla** [comment]
Thanks for checking. I am still receiving the same error message. 

Double-check dependencies: [ python==3.7.12, keras & tensorflow==2.8.0, scikit-learn==0.21.3 ]

See error message below:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/jd/xc5v3g2j5nz52rmv0jd4dn8h0000gn/T/ipykernel_3651/765365927.py in <module>
      1 vectorized = vectorize(df.payload, model_id).sort_indices()
----> 2 preds = pd.DataFrame(model.predict(vectorized))
      3 df = df.join(preds)
      4 df

~/opt/anaconda3/envs/ojs/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~/opt/anaconda3/envs/ojs/lib/python3.7/site-packages/keras/engine/data_adapter.py in select_data_adapter(x, y)
    985         "Failed to find data adapter that can handle "
    986         "input: {}, {}".format(
--> 987             _type_name(x), _type_name(y)))
    988   elif len(adapter_cls) > 1:
    989     raise RuntimeError(

ValueError: Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'NoneType'>
```

**Comment by tgweber** [comment]
I could reproduce your problem. Please drop the .sort_indices() as in https://github.com/tgweber/fosc/blob/1e774dbdabf989c3f45c6f72ea08ee02fd40cf7a/README.md?plain=1#L87
I am a bit confused, how this .sort_indices() came into your original post, since I cannot find it in my git history in the README.md. Please try again by re-copying the quickstart-example. I just did that with your python version and besides some warnings it worked for me.

**Comment by jballhalla** [comment]
I had called .sort_indices() in response to a previous issue opened on this channel, while I was initially debugging. 

fosc is now working for me. Thanks for your help and patience!
